<?php
$pagetitle = 'Cobalt Warhead Guide (Legacy)';
include $_SERVER['DOCUMENT_ROOT'].'/inc/head.inc';
?>
</head>
<body id="articles">
<?php include $_SERVER['DOCUMENT_ROOT'].'/inc/menu.inc'; ?>
  <div class="center-h" id="container">
    <div id="main-content">
      <a name="article4"></a>
      <h2>Cobalt Warhead Guide</h2>
      <p>Author: Aceflyer</p>
      <div class="tut">
        <p><i>One time use only. Use with caution.<br>Creates an earth-shattering kaboom when you die. Can be used to eliminate an entire base.</i></p>
        <p>-from <i>?iteminfo cobalt warhead</i> Cobalt Warhead. This mysterious, ominously described item is the single most powerful weapon in Hyperspace. You may have heard it mentioned whenever prospects looked bleak for your freq: "COBALT!" "USE COBALT!" Indeed, the fame of this item - so secret and l33t that it isn't publicly listed in any buy menu - has grown so much that the Cobalt Warhead has attained almost mythic proportions as a purportedly unstoppable "auto-win" device for any situation.</p>
        <p>This short page on the Cobalt Warhead aims to defuse some of these myths and exaggerations, as well as provide tips and strategies on when and how to best use this item in game.</p>
        <p>The first thing to emphasize is that the Cobalt Warhead item costs $50000 and is one-time use only. If you buy Cobalt Warhead in a given ship, the Warhead will be automatically released upon your very next death after buying the Warhead, immediately after which the item will be removed from your ship. Note that you <b>cannot</b> manually release the Warhead before you die, <b>nor</b> can you save the Warhead for future use by preventing the Warhead from launching when you die. Also, the Cobalt Warhead item is classified as Alien Technology (even though it isn't listed under the Alien Technology buy menu), so if a given ship of yours is already equipped with, say, Field Launcher, you won't be able to get Cobalt Warhead on that ship.</p>
        <p>Now, the Warhead is *powerful*, and it <b>can</b> "eliminate an entire base" <b>if used properly</b>, but it isn't simply a massive omnidirectional bomb that explodes when you die (while carrying it) and destroys all enemy ships within a certain radius of where your ship exploded. Rather, the Warhead comes out of the nose of your ship (where bombs normally come out) and flies away from your position in the direction your ship's nose was pointing when your ship blew up. It will then proceed to destroy any enemy ships it encounters along its path. Hence, when carrying a Cobalt Warhead, <b>it is important to aim your ship's nose in the direction of your targeted enemy ships when you get killed</b>. If your ship's nose is aimed away from your targeted enemy ships, the Warhead will fail to destroy your targets and you will have irrevocably wasted $50000 without getting any results.</p>
        <p>The second thing to note is that the faster you were flying 'forward' when your ship blows up, the faster the Warhead's speed will be when it launches from your ship's nose. The faster the Warhead's speed is, the more distance it will cover before it fizzles out, and hence the more enemy ships it will destroy before it fizzles out. Also, the faster the Warhead's speed is, the less likely enemy ships will be able to get out of the way in time. Hence, in addition to the guideline already set forth, <b>it is important to fly as fast as possible in the direction of your targets</b>.</p>
        <p>Finally (as if the above weren't enough to worry about!), it turns out that the Warhead can actually be stopped/jammed/intercepted by an enemy ship if that ship is sufficiently close to the Warhead's launching point (i.e., your ship's nose). So if there is an enemy ship right in front of you when you die, the Warhead will fly out, and it will be intercepted by that enemy ship. That ship will be destroyed by the Warhead, but the Warhead will then immediately fizzle out - without continuing its path of destruction! Hence, <b>it is important to try to position yourself so that there are no enemy ships right in front of your ship's nose when you die</b>.</p>
        <p>Note that Cobalt Warheads are not stopped by walls (except that they are blocked (as in absorbed) by special 'thor-proof' 'double' walls - these walls partially enclose the flagrooms of the bases in Sectors 2, 3, 5, and 6, and make up the lower and right boundaries of the minibase in the center area), so you should not be concerned about normal walls when strategizing the use of your Warhead.</p>
        <p>From the above guidelines, one can make some inferences about when the use of a Cobalt Warhead might be logical. Since the Warhead costs $50000 a pop, it is generally not worth it to use it in the center area. In fact, generally, no matter how many enemy ships a single Warhead takes out, you'll never recover the $50000 you spent on the Warhead, so this item is not useful in terms of helping you make money. So typically the Cobalt Warhead is used (mostly for the sake of pride; maybe to give your freq a chance) when you are on a basing team and you and your freqmates are bogged down, with the enemy team closely clustered together in a very solid defensive position, reinforcing each other to the point that thors aren't effective enough and no one can get close enough to field them. In this situation, a Cobalt Warhead, used in accordance with the three guidelines set forth above, can be used to eliminate the entire enemy team (or very nearly the entire enemy team).</p>
        <p>Of course, situations are seldom this 'ideal', and a Cobalt Warhead may still be very effective even if, say, the enemy team isn't that closely clustered together. However, remember that if the enemy team is pretty loosely situated, a single Warhead may take out a few enemy ships, but will definitely not be able to eliminate the entire base. Take care not to get in a situation where you are at risk of dying while being violently jostled around in the base; if the jostling results in your ship's nose happening to be pointing not at the enemy team when you die, your Warhead will be effectively wasted. Try to get as close as possible to the enemy team and make sure you are flying forward into enemy fire (remember, the Warhead is only released when you die) as fast as possible (so the enemy team can't get out of the way in time) with, of course, your ship's nose pointing straight toward the enemy team. And finally, be very careful not to die before reaching the location where you want to launch the Warhead. If you inadvertantly get killed in center, for example, before ever reaching the base where the action's going on, your Warhead will launch in center and you will have wasted $50000 for nothing (or nearly nothing).</p>
        <p>Good luck with the Cobalt Warhead!</p>
      </div>
    </div>
  </div>
<?php include $_SERVER['DOCUMENT_ROOT'].'/inc/foot.inc'; ?>