    <hr class="section-division">
    <div id="foot" class="container">
      <div id="nav-tools">
        <img id="foot-logo" src="/hs_logo.png"><br>
        <form id="search" action="/search.php">
          <input name="q" type="search" id="tipue_search_input" placeholder="Search Hyperspace" required>
        </form>
      </div>
      <nav id="site-map" role="navigation">
        <ul id="cat-main">
          <li><a href="/intro.php">Introduction</a>
            <ul>
              <li><a href="/intro.php#about">What is Hyperspace?</a></li>
              <li><a href="/intro.php#history">History</a></li>
              <li><a href="/intro.php#gameplay">Getting Started</a> (Tutorials)</li>
              <li><a href="/intro.php#commands">Common Commands</a></li>
              <li><a href="/intro.php#arenas">Arenas</a></li>
              <li><a href="/intro.php#locations">Key Locations</a></li>
            </ul>
          </li>
          <li>Reference
            <ul>
              <li><a href="/ref/news.php">news.txt</a></li>
              <li><a href="/ref/glossary.php#common-terms">Common Terminology</a></li>
              <li><a href="/ref/glossary.php#ship-properties">Ship Properties Reference</a></li>
              <li><a href="/ref/index.php#staff">Zone Staff and Key Individuals</a></li>
              <li><a href="/ref/index.php#rules">Rules and Guidelines</a></li>
            </ul>
          </li>
          <li><a href="/tools/">Tools</a>
            <ul>
              <li><a href="/tools/browse.php#ship-browser">Ship Browser</a></li>
              <li><a href="/tools/browse.php#item-browser">Item Browser</a></li>
              <li><a href="/tools/build.php">Ship Builder</a></li>
              <li><!--<a href="/tools/calc.php">-->Calc<!--</a>--></li>
            </ul>
          </li>
          <li><a href="/dev/">Development</a>
            <ul>
              <li><a href="/dev/index.php#zone">Zone Server and Configuration</a></li>
              <li><a href="/dev/index.php#website">Website</a></li>
              <li><a href="/dev/index.php#bot">Monkeybot</a></li>
              <li><a href="/dev/index.php#chatnet-for-android">ChatNet for Android</a></li>
              <li><a href="/dev/index.php#other">Other Projects</a></li>
            </ul>
          </li>
          <li><a href="http://subspace.co/index.php?/forum/15-hyperspace/">Discussion</a> (Forums)
            <!--
            <ul>
              <li><a href="http://subspace.co/index.php?forum/15-hyperspace/">subspace.co</a></li>
              <li><a href="http://www.subspaceforum.com/forum/hyperspace">SubSpace Forum</a></li>
            </ul>
            -->
          </li>
          <li>Posterity
            <ul>
              <li><a href="/posterity/articles.php">Legacy Articles</a>
                <ul>
                  <li><a href="/posterity/article2.php">A Newbie's Guide to Hyperspace</a></li>
                  <li><a href="/posterity/article4.php">Cobalt Warhead Guide</a></li>
                  <li><a href="/posterity/article3.php">Antideath Guide</a></li>
                  <li><a href="/posterity/article5.php">FTL Engine Failure</a></li>
                  <li><a href="/posterity/article6.php">Iteminfo and Shipstatus</a></li>
                  <li><a href="/posterity/article7.php">One Time Use</a></li>
                  <li><a href="/posterity/article8.php">Ship Guide and Quick Reference</a></li>
                  <li><a href="/posterity/article9.php">Special Events</a></li>
                  <li><a href="/posterity/article10.php">Utilities</a></li>
                  <li><a href="/posterity/article11.php">General Tips</a></li>
                  <li><a href="/posterity/article12.php">Zone Rules</a></li>
                  <li><a href="/posterity/article13.php">Chatnut</a></li>
                  <li><a href="/posterity/article14.php">All About Armor</a></li>
                </ul>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
    <script src="/hs.js"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
      ga('create', 'UA-8872962-7', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>