<!DOCTYPE html>
<html>
  <head>
    <title>SSCE Hyperspace : <?=$pagetitle?></title>
    <meta name="description" content="The one and only SubSpace Continuum zone: SSCE Hyperspace." />
    <meta name="keywords" content="SSCE Hyperspace,Subspace Continuum,Subspace Continuum zone" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300' rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400' rel='stylesheet' type='text/css' />
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="/hs.css" />