        <div class="vertical-nav-links">
          <div>
            <a id="about-link" class="nav-category" href="/intro.php">Introduction</a>
            <ul class="sub-links" id="about-links">
              <li><a href="/intro.php#about">About</a></li>
              <li><a href="/intro.php#history">History</a></li>
              <li><a href="/intro.php#gameplay">Gameplay</a></li>
            </ul>
          </div>
          <div>
            <a id="ref-link" class="nav-category" href="/reference.php">Reference</a>
            <ul class="sub-links" id="ref-links">
              <li><a href="/news.php">news.txt</a></li>
              <li><a href="/glossary.php">Glossary</a></li>
              <li><a href="/reference.php#staff">Staff</a></li>
              <li><a href="/reference.php#rules">Rules</a></li>
            </ul>
          </div>
          <div>
            <a id="tool-link" class="nav-category" href="/tools.php">Tools</a>
            <ul class="sub-links" id="tool-links">
              <li>Browser</li>
              <li><a href="/build.php">Builder</a></li>
              <li>Calc</li>
            </ul>
          </div>
          <div>
            <a id="dev-link" class="nav-category" href="/development.php">Development</a>
            <ul class="sub-links" id="dev-links">
              <li><a href="/development.php#zone">Zone</a></li>
              <li><a href="/development.php#website">Website</a></li>
              <li><a href="/development.php#bot">Bot</a></li>
            </ul>
          </div>
          <div>
            <a class="nav-category" href="http://subspace.co/index.php?/forum/15-hyperspace/" target="_blank">Discussion</a>
          </div>
          <div>
            <a id="history-link" class="nav-category" href="/posterity/articles.php">Posterity</a>
            <ul class="sub-links" id="history-links">
              <li><a href="/posterity/articles.php">Articles</a></li>
            </ul>
          </div>
        </div>