        <div class="vertical-nav-links">
          <div>
            <a id="about-link" class="nav-category" href="/intro.php">Introduction</a>
            <ul class="sub-links" id="about-links">
              <li><a href="/intro.php#about">About</a></li>
              <!--<li><a href="/intro.php#history">History</a></li>-->
              <li><a href="/intro.php#gameplay">Gameplay</a></li>
              <li><a href="/intro.php#commands">Commands</a></li>
            </ul>
          </div>
          <div>
            <a id="ref-link" class="nav-category" href="/ref/">Reference</a>
            <ul class="sub-links" id="ref-links">
              <li><a href="/ref/news.php">news.txt</a></li>
              <li><a href="/ref/glossary.php">Glossary</a></li>
              <li><a href="/ref/index.php#staff">Staff</a></li>
              <li><a href="/ref/index.php#rules">Rules</a></li>
            </ul>
          </div>
          <div>
            <a id="tool-link" class="nav-category" href="/tools/">Tools</a>
            <ul class="sub-links" id="tool-links">
              <li><a href="/tools/browse.php">Browser</a></li>
              <li><a href="/tools/build.php">Builder</a></li>
              <li>Calc</li>
            </ul>
          </div>
          <div>
            <a id="dev-link" class="nav-category" href="/dev/">Development</a>
            <ul class="sub-links" id="dev-links">
              <li><a href="/dev/index.php#zone">Zone</a></li>
              <li><a href="/dev/index.php#website">Website</a></li>
              <li><a href="/dev/index.php#bot">Bot</a></li>
            </ul>
          </div>
          <div>
            <a class="nav-category" href="http://subspace.co/index.php?/forum/15-hyperspace/" target="_blank">Discussion</a>
          </div>
          <div>
            <a id="history-link" class="nav-category" href="/posterity/articles.php">Posterity</a>
            <ul class="sub-links" id="history-links">
              <li><a href="/posterity/articles.php">Articles</a></li>
            </ul>
          </div>
        </div>