        <div class="vertical-nav-links">
          <div>
            <a id="about-link" href="#">INTRODUCTION</a>
            <ul class="sub-links" id="about-links">
              <li><a href="/intro.php#about">about</a></li>
              <li><a href="/intro.php#history">history</a></li>
              <li><a href="/intro.php#gameplay">gameplay</a></li>
            </ul>
          </div>
          <div>
            <a id="ref-link" href="#">REFERENCE</a>
            <ul class="sub-links" id="ref-links">
              <li><a href="/news.php">news.txt</a></li>
              <li><a href="/glossary.php">glossary</a></li>
              <li><a href="/reference.php#staff">staff</a></li>
              <li><a href="/reference.php#rules">rules</a></li>
            </ul>
          </div>
          <div>
            <a id="tool-link" href="#">TOOLS</a>
            <ul class="sub-links" id="tool-links">
              <li><a href="#">browser</a></li>
              <li><a href="#">build</a></li>
              <li><a href="#">calc</a></li>
            </ul>
          </div>
          <div>
            <a id="dev-link" href="#">DEVELOPMENT</a>
            <ul class="sub-links" id="dev-links">
              <li><a href="/development.php#zone">zone</a></li>
              <li><a href="/development.php#website">website</a></li>
              <li><a href="/development.php#bot">bot</a></li>
            </ul>
          </div>
          <div>
            <a href="http://subspace.co/index.php?/forum/15-hyperspace/" target="_blank">DISCUSSION</a>
          </div>
          <div>
            <a id="history-link" href="#">POSTERITY</a>
            <ul class="sub-links" id="history-links">
              <li><a href="/posterity/articles.php">articles</a></li>
            </ul>
          </div>
        </div>